version: "3.7"

services:
  server:
    image: kunde21/gitea-arm:v1.12.1
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - APP_NAME="Git Server"
      - RUN_MODE=dev
      - DISABLE_SSH=true
    volumes:
      - type: bind
        source: /var/docker/gitea-server
        target: /data
    ports:
      - 3001:3001
    networks:
      - gitea
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s

  db:
    image: postgres:9.6.18-alpine
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - type: bind
        source: /var/docker/gitea-db
        target: /var/lib/postgresql/data
    deploy:
      mode: global
      placement:
        constraints: [node == node1.cluster]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s

networks:
  gitea:
    external: false
