version: "3.7"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.11.3
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - APP_NAME="Git Server"
      - RUN_MODE=dev
      - DISABLE_SSH=true
    volumes:
      - gitea-data:/data
    ports:
      - "3000:3000"
    networks:
      - gitea
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.name == node1.cluster]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s

volumes:
  gitea-data:
    driver: local
  mysql-data:
    driver: local
