version: "3.7"

services:
  server:
    image: kunde21/gitea-arm:v1.12.1
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - APP_NAME="Git Server"
      - RUN_MODE=dev
      - DISABLE_SSH=true
      - DOMAIN=manager.cluster
    volumes:
      - type: bind
        source: /var/docker/gitea-server
        target: /data
    networks:
      - gitea
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.gitea.rule=Host(`git.cluster`)"
        - "traefik.http.routers.gitea.entrypoints=web"
        - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s

  db:
    image: postgres:9.6.18-alpine
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - type: bind
        source: /var/docker/gitea-db
        target: /var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.node == 1]
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s

networks:
  gitea:
    external: false
  traefik:
    external: true
