version: "3.7"

services:
  visualizer:
    image: 192.168.1.25:5000/visualizer-arm
    #image: alexellis2/visualizer-arm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.visualizer.rule=Host(`swarm.cluster`)"
        - "traefik.http.routers.visualizer.entrypoints=web"
        - "traefik.http.routers.visualizer.service=visualizer"
        - "traefik.http.services.visualizer.loadbalancer.server.port=8080"
      mode: global
      placement:
        constraints: [node.role == manager]

networks:
  traefik:
    external: true
