version: "3.7"

services:
  whoami:
    image: containous/whoami
    container_name: whoami
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.whoami.rule=Host(`whoami.cluster`)"
        - "traefik.http.routers.whoami.entrypoints=web"
        - "traefik.http.routers.whoami.service=whoami"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
      mode: replicated
      replicas: 4
    networks:
      - traefik

networks:
  traefik:
    external: true
