version: "3.7"

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
      - traefik
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.swarmpit.rule=Host(`swarmpit.cluster`)"
        - "traefik.http.routers.swarmpit.entrypoints=web"
        - "traefik.http.routers.swarmpit.service=swarmpit"
        - "traefik.http.services.swarmpit.loadbalancer.server.port=8080"
  db:
    image: treehouses/couchdb:2.3.1
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
    deploy:
      placement:
        constraints: [node.labels.node == 1]
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  influxdb:
    image: influxdb:1.8.0
    volumes:
      - influx-data:/var/lib/influxdb
    networks:
      - net
    deploy:
      placement:
        constraints: [node.labels.node == 2]
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      labels:
        swarmpit.agent: "true"
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

networks:
  net:
    driver: overlay
    attachable: true
  traefik:
    external: true

volumes:
  db-data:
    driver: local
  influx-data:
    driver: local
