version: "3.7"

services:
  oled:
    image: rpi-cluster/display:latest
    privileged: true
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 30s
      placement:
        constraints: [node.role == manager]
